# Generated by Django 4.1.13 on 2024-02-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mybookmodel',
            options={},
        ),
    ]
