# Generated by Django 4.1.13 on 2024-02-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTestApp', '0002_alter_mybookmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mybookmodel',
            options={'ordering': ['-title']},
        ),
    ]
