# Generated by Django 4.1.13 on 2024-02-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTestApp', '0003_alter_mybookmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mybookmodel',
            options={},
        ),
    ]
